// This file is kept for backward compatibility
// All database types are now generated by Prisma in @/generated/prisma

// Legacy Tables type for components that haven't been migrated
export type Tables<T extends string> = any

// Re-export some common types that were previously used from supabase types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Placeholder types for services that haven't been migrated yet
export type PaymentWithRelations = {
  id: string;
  created_at: string;
  updated_at: string;
  stable_id: string;
  status: string;
  user_id: string;
  amount: number;
  months: number;
  discount: number;
  total_amount: number;
  vipps_order_id?: string;
  vipps_transaction_id?: string;
  payment_type: string;
  subscription_months?: number;
  subscription_start_date?: string;
  subscription_end_date?: string;
  stable?: any;
  user?: any;
}

export type ArticleWithRelations = {
  id: string;
  title: string;
  slug: string;
  content: string;
  excerpt?: string;
  author_id: string;
  category: string;
  tags: string[];
  published_at?: string;
  created_at: string;
  updated_at: string;
  featured_image?: string;
  is_published: boolean;
  view_count: number;
  author?: {
    id: string;
    name?: string;
    email: string;
  };
}